/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hadoop' at '7/17/15 10:23 PM' with Gradle 2.4
 *
 * @author hadoop, @date 7/17/15 10:23 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
