/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'hadoop' at '7/17/15 10:26 PM' with Gradle 2.4
 *
 * @author hadoop, @date 7/17/15 10:26 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
