/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'hadoop' at '7/17/15 10:26 PM' with Gradle 2.4
 *
 * @author hadoop, @date 7/17/15 10:26 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
